apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-demo-config
  namespace: kubernetes-demo
  labels:
    app.kubernetes.io/name: kubernetes-demo
data:
  APP_NAME: Kubernetes Demo App
  APP_ENV: development
  APP_VERSION: 1.0.0
  STUDENT_NAME: Stecy
