apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-demo-secret
  namespace: kubernetes-demo
  labels:
    app.kubernetes.io/name: kubernetes-demo
type: Opaque
stringData:
  DEMO_SECRET: super-secret-value
