apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
  namespace: kubernetes-demo
  labels:
    app.kubernetes.io/name: kubernetes-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubernetes-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
